- .gitignore
- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/GraphiteStringHandler.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
> Add hooks for blacklist/whitelist regexs for graphite listener

- proxy/pom.xml
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.thread.NonBlockingThread
> added explicit dependency on jetty-util to fix exception

- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
Need this for a hermetic deployment in which we bundle a JRE.
> Configure JCommander to accept unparsed flags.

- java-lib/src/main/java/com/wavefront/api/agent/AgentConfiguration.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
@panghy  This is the change needed to make the collector not serialize new fields that old agents don't understand.
> Set AgentConfiguration to not serialize null field values, for backward compatibiity

- java-client/src/main/java/com/wavefront/integrations/Wavefront.java
Discovered while testing DropWizard integration. The host= and any other tags don't currently have any space separating them which leads to blocked lines.
> Add a space between tags

- .gitignore
- dropwizard-metrics/3.1/README.md
- dropwizard-metrics/3.1/pom.xml
- dropwizard-metrics/3.1/src/main/java/com/wavefront/integrations/metrics/WavefrontReporter.java
- dropwizard-metrics/4.0/README.md
- dropwizard-metrics/4.0/pom.xml
- dropwizard-metrics/4.0/src/main/java/com/wavefront/integrations/metrics/WavefrontReporter.java
- pom.xml
This adds DropWizard Metrics Reporters which use the Wavefront Proxy for the stable version of DropWizard Metrics (which only supports point tags at the Reporter level) and the latest Master of DropWizard Metrics (which supports point tags at the Reporter and Metric level)
It seems like the way JVM metrics are collected has changed quite a bit since the YammerMetrics version that the existing JsonMetricsReporter uses (For instance the VirtualMachineMetrics class no longer exists). 
I have tried to implement something similar via the .includeJvmMetrics() option that can be passed to the Reporter at build time. A user could also ignore that option (it is not on by default) and add exactly whichever JVM metrics they wish to their own MetricsRegistry.
> Dropwizard metrics

- java-lib/src/main/java/com/wavefront/ingester/GraphiteDecoder.java
- java-lib/src/main/java/com/wavefront/ingester/GraphiteHostAnnotator.java
- java-lib/src/main/java/com/wavefront/ingester/IngesterFormatter.java
- java-lib/src/main/java/com/wavefront/ingester/OpenTSDBDecoder.java
- java-lib/src/test/java/com/wavefront/ingester/GraphiteDecoderTest.java
- java-lib/src/test/java/com/wavefront/ingester/GraphiteHostAnnotatorTest.java
- java-lib/src/test/java/com/wavefront/ingester/OpenTSDBDecoderTest.java
- pkg/opt/wavefront/wavefront-proxy/conf/wavefront.conf
- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
We already had a hard coded "extra" tag that could resolve to source/host which was "fqdn".
This adds the ability for a user to specify additional tags that should be used as the source in cases where neither a source= or host= tag exists
> Configureable custom source tags

- .gitignore
- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
- proxy/src/main/java/com/wavefront/agent/WriteHttpJsonMetricsEndpoint.java
- test/runner.py
- test/wavefront.conf
This was added to allow customers with older versions of collectd (without write_graphite or write_tsdb).  write_http was added in 4.8 and this allows customers who are on 4.8 or later to send stuff to our proxy via write_http.
See https://collectd.org/wiki/index.php/Plugin:Write_HTTP
Also added a test runner to make sure json is parsed correctly.  We'll need to add some more test case. It is currently testing a very simple case to catch the basics.
> add support for write_http JSON format

- pkg/README.md
- pkg/build.sh
- pkg/stage.sh
This allows us to drop-in a pre-released wavefront-jar if required.
> Split build and stage phases of the package creation.

- java-lib/src/main/java/com/wavefront/ingester/IngesterFormatter.java
- java-lib/src/test/java/com/wavefront/ingester/GraphiteDecoderTest.java
Previously with a wavefront.conf setting of `customSourceTags=fqdn` data like this:
`metric.measure 1 fqdn=hostname.company.com` would have been transformed into: `metric.measure 1 source=hostname.company.com`
With this change that would be: `metric.measure 1 source=hostname.company.com fqdn=hostname.company.com`
That has the advantage of allowing any existing queries which relied on fqdn= to continue to work.
> Do remove a custom tag when treating it as source

- pkg/opt/wavefront/wavefront-proxy/conf/wavefront.conf
- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
This pull changes the default configuration in 2 aspects:
1. Adds the new flushThreads property to the default configuration. It seems like it may be safer to explicitly set it to 4 here by default, rather than allowing the code to set it to a very large number like 32 in the case of a large machine. 
2. Disables ports 3878 and 4878 by default, but with a commented out property in wavefront.conf making it very easy to turn them on as needed.
> Improve default configuration

- java-lib/src/main/java/com/wavefront/api/AgentAPI.java
- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/QueuedAgentService.java
Backwards-compatible to older WF versions -- the "ephemeral" field is
ignored in that case.
> Support ephemeral agents in java-lib.

- pkg/opt/wavefront/wavefront-proxy/conf/wavefront.conf
The most common "new" user of the proxy is using try.wavefront.com so we should use that as the default.
> Make try the default server URL

- pkg/etc/init.d/wavefront-proxy
Service status call should return code based on the state of the service. `0` is for running service while `3` is for not running service. This change will allow automation tools like Chef/Puppet/... to restart the service in case it crashes. Currently, if the service is not running, it will not get restarted as the exit code is `0`.
> Add status exit code

- .gitignore
- java-lib/src/main/java/com/wavefront/ingester/Ingester.java
- java-lib/src/main/java/com/wavefront/ingester/OpenTSDBDecoder.java
- java-lib/src/main/java/com/wavefront/ingester/PickleProtocolDecoder.java
- java-lib/src/main/java/com/wavefront/ingester/StringLineIngester.java
- java-lib/src/main/java/com/wavefront/ingester/TcpIngester.java
- proxy/src/main/java/com/wavefront/agent/ChannelByteArrayHandler.java
- proxy/src/main/java/com/wavefront/agent/ChannelStringHandler.java
- proxy/src/main/java/com/wavefront/agent/OpenTSDBPortUnificationHandler.java
- proxy/src/main/java/com/wavefront/agent/PlainTextOrHttpFrameDecoder.java
- proxy/src/main/java/com/wavefront/agent/PointHandler.java
- proxy/src/main/java/com/wavefront/agent/PostPushDataTimedTask.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
- proxy/src/main/java/com/wavefront/agent/QueuedAgentService.java
- proxy/src/test/java/com/wavefront/agent/QueuedAgentServiceTest.java
- test/runner.py
- test/wavefront.conf
OpenTSDB actually listens for the "telnet" protocol and the HTTP protocol on a single port (4242).  It detects the data type and handles the command based on the request.
See [OpenTSDB documentation](http://opentsdb.net/docs/build/html/user_guide/writing.html#input-methods) for more details.
- This pull request adds a netty decoder similar to the one implemented in the tsd code [https://github.com/OpenTSDB/opentsdb/blob/master/src/tsd/PipelineFactory.java].  It uses the first 2 bytes to detect if the request is HTTP or telnet.  The paths for the HTTP request are checked manually instead of with JAX-RS because the [connector](https://github.com/caskdata/netty-http) to netty does not seem not very pluggable.
- The previously unsupported OpenTSDB "version" command is now supported on both …
> Support OpenTSDB telnet and HTTP protocols on a single port

- java-lib/pom.xml
- pom.xml
- proxy/pom.xml
Reduce the number of warnings during project build
> Clean up version conflicts and redundant dependencies

- java-lib/src/main/java/com/wavefront/ingester/Ingester.java
- java-lib/src/main/java/com/wavefront/ingester/StreamIngester.java
- java-lib/src/main/java/com/wavefront/ingester/TcpIngester.java
- pkg/opt/wavefront/wavefront-proxy/conf/wavefront.conf
- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/PostPushDataTimedTask.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
- proxy/src/main/java/com/wavefront/agent/PushAgentDaemon.java
- proxy/src/main/java/com/wavefront/agent/QueuedAgentService.java
Prevent point loss during proxy shutdown/restart process - stop port listeners first and drain all in-memory buffers to retry queue
> Graceful service shutdown and configure SO_LINGER

- java-lib/src/main/java/com/wavefront/ingester/StringLineIngester.java
- proxy/src/main/java/com/wavefront/agent/PointHandler.java
- proxy/src/main/java/com/wavefront/agent/PointHandlerImpl.java
- proxy/src/main/java/com/wavefront/agent/QueuedAgentService.java
- No longer convert every single point to a string just in case it throws an exception
- When splitting a batch, use a string index instead of recreating all the strings
> Reduce memory footprint

- proxy/src/main/java/com/wavefront/agent/QueuedAgentService.java
- proxy/src/main/java/com/wavefront/agent/ResubmissionTaskQueue.java
on a machine with very limited resources. 
When the number of push threads is low and there are a lot of items in the retry queue; when a  new batch is also forced to be queued, the retry loop is very likely to immediately acquire back the just released lock, not giving the push thread a chance to write to the queue - and this could last for several minutes, quickly eating up heap memory as points are accumulating in a push thread's buffers.
> Prevent OoM in a tight retry loop 

- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/PostPushDataTimedTask.java
Limit queue draining per cycle to give threads a chance to snap out of endless queueing loop
> Faster recovery after heavy queueing

- pkg/README.md
- pkg/after-install.sh
- pkg/before-remove.sh
- pkg/etc/init.d/wavefront-proxy
rpm has a package upgrade sequence that is different from dpkg - it installs the new version first, executing the after-install script, and only then it uninstalls a previous version. When proxy is upgraded from an older version to 3.26, where we no longer bundle the JRE, after-install script is executed first, it downloads and unpacks the JRE into the same location, and then rpm deletes all the JRE files as they are still considered part of the old version. 
In this PR: 
- Change the JRE directory name so rpm doesn't confuse it with the one bundled with a previous version
- For future upgrades: only delete the JRE if it's truly an uninstall, and not an upgrade.
> Fix RPM upgrade to 3.26+ on el6/el7

- proxy/src/main/java/com/wavefront/agent/config/Configuration.java
- proxy/src/main/java/com/wavefront/agent/config/MetricMatcher.java
- proxy/src/main/java/com/wavefront/agent/logsharvesting/FilebeatListener.java
- proxy/src/main/java/com/wavefront/agent/logsharvesting/LogsIngestionConfigManager.java
- proxy/src/main/java/com/wavefront/agent/logsharvesting/MetricCacheLoader.java
- proxy/src/test/java/com/wavefront/agent/logsharvesting/FilebeatListenerTest.java
If a new configuration is hotloaded into logs ingestion for the proxy,
and that new config has removed some MetricMatchers, stop reporting
those metrics that correspond to the metric matchers.
> Remove old metrics on config hotload.

- java-lib/src/main/java/com/wavefront/ingester/StringLineIngester.java
- pkg/etc/wavefront/wavefront-proxy/wavefront.conf.default
- proxy/src/main/java/com/google/common/util/concurrent/RecyclableRateLimiter.java
- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/PostPushDataTimedTask.java
- proxy/src/main/java/com/wavefront/agent/QueuedAgentService.java
- proxy/src/main/java/com/wavefront/agent/ResubmissionTask.java
Limit outgoing rate at the proxy (averaged over 1 minute), with a single limit controlling both data flows (incoming points and retry queue). Incoming points are always given a priority, and retry queue is considered ok to start processing if there is more than 1 second worth of accumulated unused "credits" (which means that the rate for incoming points is less than the limit).
> Limit rate at the proxy

- proxy/pom.xml
- proxy/src/main/java/com/wavefront/agent/ChannelByteArrayHandler.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/AgentPreprocessorConfiguration.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/PointLineReplaceRegexTransformer.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/Preprocessor.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/ReportPointReplaceRegexTransformer.java
- proxy/src/test/java/com/wavefront/agent/preprocessor/AgentConfigurationTest.java
- proxy/src/test/java/com/wavefront/agent/preprocessor/PreprocessorRulesTest.java
- proxy/src/test/resources/com/wavefront/agent/preprocessor/preprocessor_rules_invalid.yaml
- Allow pointLine scope rules for binary protocols like graphite pickle, by faking "plaintext" protocol by converting a point to a string and parsing it back. The goal is to provide temporary implementation for the same set of rules during POC trials, when Graphite and Wavefront consume the same data in parallel from carbon-relay, which can only output data in the binary pickle format. Once the trial is over, carbon-relay can be removed from the pipeline and switch back to plaintext protocol.
- Add an optional "match" condition to replaceRegex rules: when defined, apply search/replace regex only if the string matches. In some cases this can significantly simplify search/replace expressions.
> Improve preprocessor rules

- java-client/src/main/java/com/wavefront/integrations/Wavefront.java
When client connection to the proxy is broken, try to resolve the proxy host name again in case the DNS entry has changed. Requires networkaddress.cache.ttl or sun.net.inetaddr.ttl security property to be set to a positive number (30 or 60 is a good default).
> Attempt to resolve DNS on connect()

- proxy/src/main/java/com/wavefront/agent/PointHandlerImpl.java
Switch ~agent.points.*.received.lag.* metrics back to use the pre-5.0 implementation
> Fix point lag tracking metric

- java-lib/src/main/java/com/wavefront/ingester/GraphiteHostAnnotator.java
- java-lib/src/test/java/com/wavefront/ingester/GraphiteHostAnnotatorTest.java
- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
1. InetAddress.getLocalHost() returns 127.0.1.1 on Debian - work around this issue by using the address from the first connected network interface, prefer IPv4 if available.
2. Cap auto-configured number of threads at 16, so instances running in containers on powerful hardware won't spawn too many threads
3. Disable automatic retries in HTTPClient so push threads can regain control quickly
> Misc improvements

- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
Customer request: disable RDNS lookup for remote clients and use remote IP address to annotate metrics that come without source/host instead
> Add ability to disable RDNS lookup

- proxy/src/main/java/com/wavefront/agent/QueuedAgentService.java
Background: getPostingSizerTask would quietly throw an InvalidObjectState exception on .finish() before it had a chance to update the histogram with sizes
> Fix missing ~agent.buffer.fill-rate metric

- java-lib/src/main/java/com/wavefront/api/agent/AgentConfiguration.java
- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
The changes allow the agents to shutdown during the check-in cadence if the server indicates that agent needs to be closed.
> Add Shutoff agent feature controlled at check-in

- java-lib/src/main/java/com/wavefront/common/MetricsToTimeseries.java
- java-lib/src/main/java/com/wavefront/metrics/JsonMetricsGenerator.java
- java-lib/src/test/java/com/wavefront/metrics/JsonMetricsGeneratorTest.java
- yammer-metrics/src/main/java/com/wavefront/integrations/metrics/SocketMetricsProcessor.java
- yammer-metrics/src/main/java/com/wavefront/integrations/metrics/WavefrontYammerMetricsReporter.java
- yammer-metrics/src/test/java/com/wavefront/integrations/metrics/WavefrontYammerMetricsReporterTest.java
Also fix a bug where mean was mis-reported as one-minute-rate for
Metered metrics.
> Allow WavefrontYammerMetricsExporter to prepend group names to outbound metrics.

- dropwizard-metrics/3.1/src/main/java/com/wavefront/integrations/metrics/WavefrontReporter.java
- dropwizard-metrics/4.0/src/main/java/com/wavefront/integrations/metrics/WavefrontReporter.java
- java-lib/src/main/java/com/wavefront/common/MetricsToTimeseries.java
- java-lib/src/main/java/com/wavefront/common/Pair.java
- java-lib/src/main/java/com/wavefront/metrics/JsonMetricsGenerator.java
- java-lib/src/test/java/com/wavefront/metrics/JsonMetricsGeneratorTest.java
- yammer-metrics/src/main/java/com/wavefront/integrations/metrics/SocketMetricsProcessor.java
- yammer-metrics/src/main/java/com/wavefront/integrations/metrics/WavefrontYammerMetricsReporter.java
- yammer-metrics/src/test/java/com/wavefront/integrations/metrics/WavefrontYammerMetricsReporterTest.java
1) Optionally add JVM metrics, similarly to JsonMetricsGenerator.
Refactor that bit to use common code.
2) Break timers into their duration/rate parts, similarly to
JsonMetricsGenerator and DISsimilarly to WavefrontDropwizardMetricsReporter.
> Compatibility changes to WavefrontYammerMetricsReporter:

- proxy/brew/wfproxy
Added a basic shell script for the Homebrew installation of the proxy. This will be installed under `/usr/local/bin/wfproxy`.
Had discussed out of band with Mori and he suggested to put in a new brew subdirectory under java/proxy.
> Shell script for wavefront homebrew installation

- java-lib/src/main/java/com/wavefront/ingester/IngesterFormatter.java
- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/PointHandlerImpl.java
- proxy/src/main/java/com/wavefront/agent/PostPushDataTimedTask.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
- proxy/src/main/java/com/wavefront/agent/config/ReportableConfig.java
- proxy/src/main/java/com/wavefront/agent/histogram/MapLoader.java
- proxy/src/main/java/com/wavefront/agent/histogram/MapSettings.java
- proxy/src/main/java/com/wavefront/agent/histogram/PointHandlerDispatcher.java
- proxy/src/main/java/com/wavefront/agent/histogram/Utils.java
- proxy/src/main/java/com/wavefront/agent/histogram/accumulator/AccumulationCache.java
- proxy/src/main/java/com/wavefront/agent/histogram/accumulator/AccumulationTask.java
- proxy/src/test/java/com/wavefront/agent/histogram/PointHandlerDispatcherTest.java
- proxy/src/test/java/com/wavefront/agent/histogram/accumulator/AccumulationTaskTest.java
- Separate Chronicle Maps with their own settings for different aggregation intervals
- Configuration setting to bypass Caffeine memory cache to reduce memory use for "many time series" use case (as opposed to "few time series, very high frequency data" use case). 
- Persist Chronicle Map settings and re-initialize accumulator maps with new settings and migrate data when config settings change  
- Allow Chronicle Map growth beyond originally configured values (+ log a warning every 10 seconds if it exceeds 1.5x the originally configured size)
- Maintain separate timestamp index on Chronicle Map to avoid iterating through the entire collection of AgentDigest values as it triggers deserialization
- Better hash function for histogramKey
> Histogram refactoring/performance improvements

- proxy/pom.xml
It looks like the removal of maven-shade plugin broke the .rpm/.deb packaging process.
Before proxy 3.17 uber jars were built using maven-assembly plugin, however, we are using a newer version of maven-assembly now that no longer supports custom output file names; and maven-shade seems to be the officially recommended way of building uber jars.
> Bring back maven-shade for uber jar building

- java-lib/src/main/java/com/wavefront/api/agent/AgentConfiguration.java
- java-lib/src/main/java/com/wavefront/ingester/HistogramDecoder.java
- java-lib/src/test/java/com/wavefront/ingester/HistogramDecoderTest.java
- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/PostSourceTagTimedTask.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
- proxy/src/main/java/com/wavefront/agent/histogram/QueuingChannelHandler.java
- Changed the proxy behavior so that if the agent_configuration.histogram_disabled then don't bother sending the histogram points to the server.
- Reject the points at QueuingChannelHandler.channelRead phase itself. The agent configuration is periodically polled in the checkin API and updated on the proxy.
> Changed the proxy behavior so that if the agent_configuration.histogram_disabled, then don't ingest histogram points

- java-lib/src/main/java/com/wavefront/api/WavefrontAPI.java
- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/PostSourceTagTimedTask.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
- proxy/src/main/java/com/wavefront/agent/QueuedAgentService.java
- proxy/src/main/java/com/wavefront/agent/api/ForceQueueEnabledAgentAPI.java
- proxy/src/test/java/com/wavefront/agent/QueuedAgentServiceTest.java
- proxy/src/test/java/com/wavefront/agent/SourceTagHandlerTest.java
The metadata API calls will send the token as QueryParam to the server. Also added a scheduler to run sending metadata tasks periodically.
> MONIT-6560, MONIT-6532: Fixed the SourceTag and SourceDescription ingestion from proxy

- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/ChannelStringHandler.java
- proxy/src/main/java/com/wavefront/agent/OpenTSDBPortUnificationHandler.java
- configurable httpMaxConnTotal & httpMaxConnPerRoute (capped at 200 and 100 respectively)
- change default httpRequestTimeout to 10s to match our recommended settings
- fixed: auto-retries were disabled
- fixed: fall-through logic for some blocked points  
- fixed: division by zero when no pushListenerPorts are active
- fixed: timestamp defaults to 0 instead of now() for OpenTSDB
> Configurable httpClient connection settings + misc bugfixes

- java-lib/src/main/java/com/wavefront/metrics/JsonMetricsGenerator.java
- java-lib/src/main/java/com/yammer/metrics/core/SafeVirtualMachineMetrics.java
Work around the issue in com.yammer.metrics.core.VirtualMachineMetrics: Java 9 is much more restrictive concerning reflective access to non-public fields/methods, as a result the proxy can't generate JVM metrics and register itself. This problem is specific to Mac installations, as we don't use a sterile environment with a bundled JRE there.
> Java 9 compatibility 

- java-lib/src/main/java/com/wavefront/common/MetricsToTimeseries.java
- java-lib/src/main/java/com/yammer/metrics/core/WavefrontHistogram.java
- proxy/src/main/java/com/wavefront/agent/config/LogsIngestionConfig.java
- proxy/src/main/java/com/wavefront/agent/logsharvesting/FlushProcessor.java
- proxy/src/main/java/com/wavefront/agent/logsharvesting/LogsIngester.java
- proxy/src/main/java/com/wavefront/agent/logsharvesting/ReadProcessor.java
- proxy/src/test/java/com/wavefront/agent/logsharvesting/LogsIngesterTest.java
- Add support for double-precision float samples to WavefrontHistogram
- Use WavefrontHistogram internally for logs ingestion 
- Add ability to export stats from WavefrontHistogram in legacy Histogram format (all stats default to zeroes for empty histograms), controlled by reportEmptyHistogramStats setting in logsingestion.yaml config
> PUB-118 fix (logs ingestion histogram precision)

- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
Don't go through the shutdown sequence twice and let shutdownHook run its course
> MONIT-8612 Correct shutdown sequence for remote shut-off

- pkg/after-install.sh
- pkg/etc/init.d/wavefront-proxy
This is standard behavior -- otherwise the proxy will come up for the first
time without there being any opportunity to configure it. A conditional
restart ("condrestart") is a pretty standard way to do "restart me, but
only if I was already running"
> only restart wavefront-proxy on package install if already runniing

- .gitignore
- dropwizard-metrics/3.1/src/main/java/com/wavefront/integrations/metrics/WavefrontReporter.java
- dropwizard-metrics/dropwizard-metrics-wavefront/pom.xml
- java-client/pom.xml
- java-client/src/main/java/com/wavefront/integrations/WavefrontDirectSender.java
- java-client/src/test/java/com/wavefront/integrations/WavefrontDirectSenderTest.java
- java-lib/pom.xml
- java-lib/src/main/java/com/codahale/metrics/DeltaCounter.java
- java-lib/src/main/java/com/wavefront/api/DataIngesterAPI.java
- java-lib/src/main/java/com/wavefront/api/DataIngestorAPI.java
- java-lib/src/main/java/com/wavefront/common/Constants.java
- java-lib/src/main/java/com/wavefront/common/NamedThreadFactory.java
- java-lib/src/main/java/com/wavefront/ingester/ReportPointIngesterFormatter.java
- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/PostPushDataTimedTask.java
- proxy/src/main/java/com/wavefront/agent/PostSourceTagTimedTask.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
- proxy/src/main/java/com/wavefront/agent/QueuedAgentService.java
MONIT-7066: Added direct ingestion/delta metrics support for Java.
Note: @basilisk487 's PR (https://github.com/wavefrontHQ/java/pull/270) includes changes to the WavefrontReporter. I can merge his changes into this PR once it is merged into master before this is merged.
> Added direct ingestion/delta metrics support

- pkg/etc/wavefront/wavefront-proxy/preprocessor_rules.yaml.default
- proxy/src/main/java/com/wavefront/agent/preprocessor/AgentPreprocessorConfiguration.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/PointLineBlacklistRegexFilter.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/PointLineReplaceRegexTransformer.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/PointLineWhitelistRegexFilter.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/PreprocessorRuleMetrics.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/ReportPointAddTagIfNotExistsTransformer.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/ReportPointAddTagTransformer.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/ReportPointBlacklistRegexFilter.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/ReportPointDropTagTransformer.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/ReportPointExtractTagIfNotExistsTransformer.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/ReportPointExtractTagTransformer.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/ReportPointForceLowercaseTransformer.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/ReportPointRenameTagTransformer.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/ReportPointReplaceRegexTransformer.java
- proxy/src/main/java/com/wavefront/agent/preprocessor/ReportPointWhitelistRegexFilter.java
- proxy/src/test/java/com/wavefront/agent/preprocessor/AgentConfigurationTest.java
- proxy/src/test/java/com/wavefront/agent/preprocessor/PreprocessorRulesTest.java
- proxy/src/test/resources/com/wavefront/agent/preprocessor/preprocessor_rules.yaml
- proxy/src/test/resources/com/wavefront/agent/preprocessor/preprocessor_rules_invalid.yaml
- New rule type "extractTagIfNotExists"
- extractTag and extractTagIfNotExists support modifying input data as well (i.e. create new tag from a portion of a metric name, and remove it from the metric name as one operation)
- Track number of times preprocessor rule has been invoked (to make calculating success ratios and identifying CPU hogs easier)
> Preprocessor improvements

- dropwizard-metrics/3.1/src/main/java/com/wavefront/integrations/metrics/WavefrontReporter.java
- dropwizard-metrics/4.0/src/main/java/com/wavefront/integrations/metrics/WavefrontReporter.java
This request accommodate changes to build a new wavefrontreporter with existing wavefront connection. (There are chances that tcp connection might be exhausted while sending multiple metrics to server with change in reporter level point tags and building a new client everytime. This code will take care of reusing existing connection while building a new wavefront reporter.)
> TCP connection reuse in building new wavefrontreporter

- pkg/Dockerfile
* This is to fix the error in building wf-proxy-builder docker image
* Broken Jenkins job:  https://jenkins-dev.corp.wavefront.com/job/ProxyJava_2_Package/82/console
* Error log:
```
18:10:34 Step 8/11 : RUN gem install fpm --version 1.6.2
18:10:34  ---> Running in 42bf5564f93d
18:10:35 [91mERROR:  Error installing fpm:
18:10:35 	ruby-xz requires Ruby version >= 2.3.0.
```
* Related webpages: https://github.com/jordansissel/fpm/issues/1493, https://github.com/jordansissel/fpm/pull/1494
* Working Jenkins build (after upgrade fpm to 1.10.0): https://jenkins-dev.corp.wavefront.com/job/ProxyJava_2_Package/84/
> change fpm to version 1.10.0

- dropwizard-metrics/dropwizard-metrics5/README.md
- dropwizard-metrics/dropwizard-metrics5/pom.xml
- dropwizard-metrics/dropwizard-metrics5/src/main/java/com/wavefront/integrations/metrics/WavefrontDropwizardReporter.java
- dropwizard-metrics/dropwizard-metrics5/src/main/java/com/wavefront/integrations/metrics/WavefrontReporter.java
- examples/dropwizard-metrics5/dependency-reduced-pom.xml
- examples/dropwizard-metrics5/pom.xml
- examples/dropwizard-metrics5/src/main/java/com/wavefront/examples/DirectReporting.java
- examples/dropwizard-metrics5/src/main/java/com/wavefront/examples/ProxyReporting.java
- java-lib/pom.xml
- java-lib/src/main/java/io/dropwizard/metrics5/DeltaCounter.java
- java-lib/src/main/java/io/dropwizard/metrics5/jvm/SafeFileDescriptorRatioGauge.java
- pom.xml
Implement WavefrontDropwizardReporter based on dropwizard version 5.0.0-rc2. Add examples for proxy based reporting as well as sending metrics directly to Wavefront.
> Add a Wavefront Reporter based on Dropwizard 5.0.0-rc2

- .gitignore
- dropwizard-metrics/dropwizard-metrics/pom.xml
- dropwizard-metrics/dropwizard-metrics5/pom.xml
- dropwizard-metrics/dropwizard-metrics5/src/main/java/com/wavefront/integrations/dropwizard_metrics5/WavefrontReporter.java
- examples/dropwizard-metrics5/src/main/java/com/wavefront/examples/DirectReporting.java
- examples/dropwizard-metrics5/src/main/java/com/wavefront/examples/ProxyReporting.java
Changed the package name for the WavefrontReporter for 5.0 to com.wavefront.integrations.dropwizard_metrics5.WavefrontReporter to avoid conflict with existing reporter com.wavefront.integrations.metrics.WavefrontReporter
> Changed the package name for the WavefrontReporter 

- pkg/etc/wavefront/wavefront-proxy/preprocessor_rules.yaml.default
- proxy/src/main/java/com/wavefront/agent/preprocessor/AgentPreprocessorConfiguration.java
- proxy/src/test/resources/com/wavefront/agent/preprocessor/preprocessor_rules.yaml
to reduce confusion. replaceSource is still supported for backwards compatibility.
> Rename replaceSource to replaceInput in extractTag* rules 

- dropwizard-metrics/dropwizard-metrics-wavefront/pom.xml
- dropwizard-metrics/dropwizard-metrics/pom.xml
- dropwizard-metrics/dropwizard-metrics5/pom.xml
- examples/dropwizard-metrics5/pom.xml
- java-client/pom.xml
- java-lib/pom.xml
- open_source_licenses.txt
- pom.xml
- proxy/pom.xml
- yammer-metrics/pom.xml
Reverts wavefrontHQ/java#302 as the examples module was added to top level in error.
> Revert "Release v4.30"

- proxy/src/main/java/com/wavefront/agent/PushAgent.java
- proxy/src/main/java/com/wavefront/agent/histogram/MapLoader.java
- proxy/src/main/java/com/wavefront/agent/histogram/accumulator/AccumulationCache.java
- proxy/src/test/java/com/wavefront/agent/histogram/accumulator/AccumulationCacheTest.java
- Increase default maxBloatSize to 1000
- Make ChronicleMap allocation failure error message more user friendly 
- Additional metrics to detect increased IO caused by memory cache pressure (also due to incorrectly configured accumulator size)
> PUB-136: improve histogram resilience in gross misconfiguration scenarios

- proxy/src/main/java/com/wavefront/agent/listeners/ChannelStringHandler.java
What the change is about:
This PR will modify ChannelStringHandler.java to have the ability to sample and log RAW data string that is coming into Wavefront Proxy, before the data gets pre-processed. This will allow users to monitor and troubleshoot their incoming data in a raw form that will make it easy to detect any incorrect or missed out pre-processing rules or simply see if their source data is in the right format.
This feature can be enabled by setting the following system properties when starting up the proxy:
wavefront.proxy.lograwdata = (true|false)
wavefront.proxy.lograwdata.sample-rate = (double value, between 0.0d ~ 1.0d)
Also, you can enable the logging behavior dynamically by setting the "RawDataLogger" in java logging to "FINE" level. Log will be suppressed when either the …
> Wavefront Proxy raw data logging

- pkg/Dockerfile
Try to fix the following issue while building proxy-builder docker image.
```
11:40:05 Step 4/11 : RUN curl -L get.rvm.io | bash -s stable
11:40:05  ---> Running in 1dd8d835b54d
11:40:05 [91m  % Total    % Received % Xferd  Average Speed   Time    Time     Time  C[0m[91murrent
11:40:05                                  Dload  Upload [0m[91m  Total   Spent    Left  Speed
11:40:05 
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[0m[91m
194   194  194   194    0     0    993      0 --:--:-- --:--:-- --:--:--  2365[0m[91m
0   194    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[0m[91m
100 24593  100 24593    0     0  75741      0 --:--:-- --:--:-- --:--:-- 1334k
11:40:05 [0mDownloading https://github.com/rvm/rvm/archive/1.29.6.tar.gz …
```
> fix proxy-builder docker image build issue

- proxy/src/main/java/com/wavefront/agent/listeners/ZipkinPortUnificationHandler.java
Handling zipkin errors. Zipkin spans usually propagate errors with key='error' and value='actual error message'. We want to ignore this error message for now. Instead report it as 'error'='true' so that the span shows up as RED in the UI.
> Handle zipkin errors

- pkg/Dockerfile
This is a suggestion from https://github.com/rvm/rvm/issues/3110.
Although last night I manage to pass the proxy-builder pacakging build stage, yet I think it's because the gpg keyserver was back to normal. Even that, I think it's no harm to commit this code "--homedir /root/.gnupg" to the Dockerfile since it might solve the gpg keyserver issue in the future
> add '--homedir /root/.gnupg' to the front

- proxy/src/main/java/com/wavefront/agent/listeners/tracing/JaegerThriftCollectorHandler.java
- proxy/src/main/java/com/wavefront/agent/listeners/tracing/ZipkinPortUnificationHandler.java
- proxy/src/test/java/com/wavefront/agent/listeners/tracing/JaegerThriftCollectorHandlerTest.java
- proxy/src/test/java/com/wavefront/agent/listeners/tracing/ZipkinPortUnificationHandlerTest.java
Having empty tags is not an error in Jaeger's and Zipkin's spans but those spans get silently rejected by Wavefront server.
This PR filters the empty tags for both the protocol.
> Added filtering of empty tags in Jaeger and Zipkin spans

- pkg/Dockerfile
Error in build:
```
ERROR:  Error installing fpm:
The last version of childprocess (>= 0) to support your Ruby & RubyGems was 1.0.1. Try installing it with `gem install childprocess -v 1.0.1` and then running the current command again
childprocess requires Ruby version >= 2.3.0. The current ruby version is 2.0.0.598.
```
> ESO-1291, Fix fpm installation and update DockerFile

- proxy/docker/Dockerfile
Fix following error as the gpg was not imported successfully.
```
Err:1 https://packagecloud.io/wavefront/proxy/ubuntu bionic InRelease
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1FA5B6918EA8F2D0
GPG error: https://packagecloud.io/wavefront/proxy/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1FA5B6918EA8F2D0
E: The repository 'https://packagecloud.io/wavefront/proxy/ubuntu bionic InRelease' is not signed.
The command '/bin/sh -c apt-get -y update' returned a non-zero code: 100
```
> Fix DockerFile

- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
- proxy/src/main/java/com/wavefront/agent/handlers/AbstractReportableEntityHandler.java
- proxy/src/main/java/com/wavefront/agent/handlers/DeltaCounterAccumulationHandlerImpl.java
- proxy/src/main/java/com/wavefront/agent/handlers/HistogramAccumulationHandlerImpl.java
- proxy/src/main/java/com/wavefront/agent/handlers/ReportPointHandlerImpl.java
- proxy/src/main/java/com/wavefront/agent/handlers/ReportSourceTagHandlerImpl.java
- proxy/src/main/java/com/wavefront/agent/handlers/ReportableEntityHandlerFactoryImpl.java
- proxy/src/main/java/com/wavefront/agent/handlers/SpanHandlerImpl.java
- proxy/src/main/java/com/wavefront/agent/handlers/SpanLogsHandlerImpl.java
- proxy/src/main/java/com/wavefront/agent/listeners/JsonMetricsPortUnificationHandler.java
- proxy/src/main/java/com/wavefront/agent/listeners/WriteHttpJsonPortUnificationHandler.java
- proxy/src/test/java/com/wavefront/agent/handlers/ReportSourceTagHandlerTest.java
test locally on invalid point to 2878, invalid span to 30000, invalid histogram to 40000, non-delta counter to 50000
- different loggers in config.ini, all loggers enabled in log4j2 -> different log files
- no logger in config.ini, all logger enabled in log4j2 -> all in blockedPoints
- span/histogram logger in config,  all loggers enable in log4j2 -> span/histogram log file separate, others go to blockedPoints
- span/histogram logger in config,  corresponding enable in log4j2 -> span/histogram log file only
- No logger in config, no log4j2 -> no log file, console is fine
> support different blocked entity log

- proxy/src/main/java/com/wavefront/agent/listeners/DataDogPortUnificationHandler.java
- proxy/src/test/java/com/wavefront/agent/PushAgentTest.java
Pulls device= as a tag on relevant DataDog metrics.
> Include a device= tag on any relevant time-series

- proxy/pom.xml
- proxy/src/main/java/com/wavefront/agent/listeners/DataDogPortUnificationHandler.java
- proxy/src/test/java/com/wavefront/agent/PushAgentTest.java
- proxy/src/test/resources/com.wavefront.agent/ddTestTimeseries.json
When DataDog sends statsd counter data the JSON contains a value that when displayed by DataDog is multiplied by the "interval" property supplied in the JSON.
This change allows Wavefront to store and render that same value. The modified value also matches what the telegraf statsd input plugin sends for the same DogStatsD data so this seems to be a quirk of how DataDog sends and parses the data.
> Handle data from DataDog of type:rate

- proxy/src/main/java/com/wavefront/agent/ProxyConfig.java
- proxy/src/main/java/com/wavefront/agent/listeners/tracing/SpanDerivedMetricsUtils.java
1. This PR allows the custom tag filter `span.kind`, to appear on P0/P1 application status page. The dropdown menu under `span.kind` contains the value of `client`, `server` or `unknown` (by default).
2. Tested with Jaeger/Zipkin integration: span data being sent through wavefront proxy can be filtered on P0/P1 through `span.kind` dropdown menu.
> Promote span.kind as RED metrics

- proxy/src/main/java/com/wavefront/agent/listeners/DataDogPortUnificationHandler.java
- proxy/src/test/java/com/wavefront/agent/PushAgentTest.java
- proxy/src/test/resources/com.wavefront.agent/ddTestSystemMetadataOnly.json
- proxy/src/test/resources/com.wavefront.agent/ddTestTimeseries.json
We saw a case where "tags" were being supplied in datadog.yaml but were not showing up in Wavefront. It was due to the fact that no "metrics" were being sent in the data sent to the "/intake" endpoint and therefore the host-tags were not being processed. 
This PR ensures that host-tags are always processed if they exist in the data.
> Cache DD host tags even if no metrics are present

- proxy/src/main/java/com/wavefront/agent/config/MetricMatcher.java
1. Prevent log message parsing to contain tags with empty values from being added to the telemetry datum.
> Updated MetricsMatcher

- proxy/src/main/java/com/wavefront/agent/listeners/tracing/JaegerThriftUtils.java
- proxy/src/main/java/com/wavefront/agent/listeners/tracing/TracePortUnificationHandler.java
- proxy/src/main/java/com/wavefront/agent/listeners/tracing/ZipkinPortUnificationHandler.java
- proxy/src/test/java/com/wavefront/agent/HttpEndToEndTest.java
- proxy/src/test/java/com/wavefront/agent/PushAgentTest.java
- proxy/src/test/java/com/wavefront/agent/listeners/tracing/JaegerPortUnificationHandlerTest.java
- proxy/src/test/java/com/wavefront/agent/listeners/tracing/JaegerTChannelCollectorHandlerTest.java
- proxy/src/test/java/com/wavefront/agent/listeners/tracing/ZipkinPortUnificationHandlerTest.java
No need to sample a second time in the backend.
> Exclude span line data when reporting span logs

- pkg/Dockerfile
docker build for pkg/Dockerfile is failing with following error:
```
[91mERROR:  Error installing fpm:
The last version of ffi (>= 0) to support your Ruby & RubyGems was 1.12.2. Try installing it with `gem install ffi -v 1.12.2` and then running the current command again
ffi requires Ruby version >= 2.3. The current ruby version is 2.0.0.598.
```
> version lock ffi to fix fpm installation

- proxy/src/main/java/com/wavefront/agent/listeners/RelayPortUnificationHandler.java
- proxy/src/main/java/com/wavefront/agent/listeners/WavefrontPortUnificationHandler.java
- proxy/src/main/java/com/wavefront/agent/listeners/tracing/JaegerGrpcCollectorHandler.java
- proxy/src/main/java/com/wavefront/agent/listeners/tracing/JaegerPortUnificationHandler.java
- proxy/src/main/java/com/wavefront/agent/listeners/tracing/JaegerProtobufUtils.java
- proxy/src/main/java/com/wavefront/agent/listeners/tracing/JaegerTChannelCollectorHandler.java
- proxy/src/main/java/com/wavefront/agent/listeners/tracing/JaegerThriftUtils.java
- proxy/src/main/java/com/wavefront/agent/listeners/tracing/TracePortUnificationHandler.java
- proxy/src/main/java/com/wavefront/agent/listeners/tracing/ZipkinPortUnificationHandler.java
Add raw span ingest metric. (~proxy.spans.\<handle\>.sent.count) 
Modify zipkin to correctly increment discardedTraces and processedBatches when span ingest feature is disabled to keep consistent with what Jaeger does currently.
> Uber sps ingestmetric

- proxy/src/main/java/com/wavefront/agent/listeners/tracing/JaegerProtobufUtils.java
- proxy/src/main/java/com/wavefront/agent/listeners/tracing/JaegerThriftUtils.java
- proxy/src/test/java/com/wavefront/agent/listeners/tracing/JaegerGrpcCollectorHandlerTest.java
- proxy/src/test/java/com/wavefront/agent/listeners/tracing/JaegerTChannelCollectorHandlerTest.java
This removes the filter for `ip` tags when forwarding Jaeger traces and fixes #423.
> Propagate all Jaeger process tags as span tags

- proxy/pom.xml
- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/ProxyConfig.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
- proxy/src/main/java/com/wavefront/agent/queueing/ConcurrentQueueFile.java
- proxy/src/main/java/com/wavefront/agent/queueing/ConcurrentShardedQueueFile.java
- proxy/src/main/java/com/wavefront/agent/queueing/DirectByteArrayOutputStream.java
- proxy/src/main/java/com/wavefront/agent/queueing/FileBasedTaskQueue.java
- proxy/src/main/java/com/wavefront/agent/queueing/InMemorySubmissionQueue.java
- proxy/src/main/java/com/wavefront/agent/queueing/InstrumentedTaskQueueDelegate.java
- proxy/src/main/java/com/wavefront/agent/queueing/QueueExporter.java
- proxy/src/main/java/com/wavefront/agent/queueing/QueueFile.java
- proxy/src/main/java/com/wavefront/agent/queueing/QueueFileFactory.java
- proxy/src/main/java/com/wavefront/agent/queueing/SQSQueueFactoryImpl.java
- proxy/src/main/java/com/wavefront/agent/queueing/SQSSubmissionQueue.java
- proxy/src/main/java/com/wavefront/agent/queueing/TapeQueueFile.java
- proxy/src/main/java/com/wavefront/agent/queueing/TaskQueue.java
- proxy/src/main/java/com/wavefront/agent/queueing/TaskQueueFactoryImpl.java
- proxy/src/main/java/com/wavefront/agent/queueing/TaskQueueStub.java
- proxy/src/test/java/com/wavefront/agent/data/DefaultEntityPropertiesFactoryForTesting.java
- proxy/src/test/java/com/wavefront/agent/handlers/ReportSourceTagHandlerTest.java
- proxy/src/test/java/com/wavefront/agent/queueing/ConcurrentShardedQueueFileTest.java
- proxy/src/test/java/com/wavefront/agent/queueing/InstrumentedTaskQueueDelegateTest.java
- proxy/src/test/java/com/wavefront/agent/queueing/QueueExporterTest.java
Instead of doubling the size of a buffer file every time we need to grow it, maintain a collection of smaller shards (128MB by default).
> Reduce disk space allocation when queueing

- pom.xml
This is to resolve the issue where proxy 9.x is rejecting internal delta counters sent by WF SDKs.
> Bump java-lib to 2020-10.1

- proxy/docker/Dockerfile-for-release
When we create WF-Proxy / proxy-next docker images for release, we need to replace the original Dockerfile's "install wf-proxy" section with lines to install the proxy from generated .deb files for the release. Until now, we were using `sed` commands to delete and replace specific lines to achieve this. This was not a scalable solution. Hence, we decided to move forward with creating our own Dockerfile-for-release to achieve this.
> Create new docker file specific for WF-proxy release (filename: Dockerfile-for-release)

- proxy/docker/Dockerfile-for-release
When we create WF-Proxy / proxy-next docker images for release, we need to replace the original Dockerfile's "install wf-proxy" section with lines to install the proxy from generated .deb files for the release. Until now, we were using sed commands to delete and replace specific lines to achieve this. This was not a scalable solution. Hence, we decided to move forward with creating our own Dockerfile-for-release to achieve this.
> Create new docker file specific for WF-proxy release (filename: Dockerrfile-for-release)

- proxy/docker/Dockerfile-for-release
Since we're moving to Photon OS, need to update Dockerfile-for-release to use tdnf and rpm to install wf-proxy instead of dpkg and deb
> [Dockerfile-for-release]: Since we're using Photon, use tdnf to install rpm instead of using dpkg and deb

- proxy/docker/Dockerfile-for-release
Add the line from original Dockerfile which copies log4j.xml to /etc/wavefront/wavefront-proxy
> [Dockerfile-for-release]: copy log4j.xml to /etc/wavefront/wavefront-proxy

- pom.xml
- proxy/pom.xml
These will avoid security CVEs caught by scan and avoid those vulnerabilities.
> Updating libraries and adding exclusions which pull in duplicate old libraries

- proxy/src/main/java/com/wavefront/agent/queueing/FileBasedTaskQueue.java
* Lib version upgrades. Updating libs : thrift  0.14.1.   netty version to 4.1.60.Final. httpclient to 4.5.13. Removing xstream since it does not seem to be used in the compilation.
* 1. Excluding guava from protubuf to avoid pulling in a bad version. 2. Adding exclusion of xstream dependency pulled.
* doing a null check for weight before initializing weight
* removing unnecessary variables
> NPE fix for FileBasedTaskQueue (#617)

- proxy/docker/Dockerfile-for-release
Remove dependency on pip/setuptools for creating docker image due to vulnerabilities.
(ESO-3192)[https://wavefront.atlassian.net/browse/ESO-3192]
> ESO-3192 fix pip/setuptools vulnerabilities in wf-proxy docker image

- proxy/docker/Dockerfile
Hit an error during GAing `10.6` due to curl.
Install curl in Dockerfile for the fix
> Fix Dockerfile by installing curl in release-10.x branch

- pkg/Dockerfile
- proxy/docker/Dockerfile
- proxy/docker/Dockerfile-for-release
- ESO:3222: change gpg keyserver from hkp://keys.gnupg.net to keyserver.ubuntu.com
- ESO:3233: install curl in Dockerfile
- ESO-3192: fix pip/setuptools vulnerabilities in wf-proxy docker image created during the release
> Multiple fixes related to 10.7 GA

- open_source_licenses.txt
- pom.xml
- proxy/pom.xml
Revert all commits created by failed builds to help re-releasing `10.12` proxy version with log4j vuln
> WFESO-4015: Revert all commits for failed proxy releases

- pom.xml
Build issues ticket for sonatype - https://issues.sonatype.org/browse/OSSRH-76156
After discussion on the above issue, created host migration request (as per comments)
Host migration request - https://issues.sonatype.org/browse/OSSRH-76161
Due to log4j day 0 vuln issues, sonatype hosts are overwhelmed.
Migrated the com.wavefront project to a new host with less load to mitigate build issues.
> WFESO-4015: Update OSSRH host to mitigate timeouts

- open_source_licenses.txt
- pom.xml
- proxy/pom.xml
Saw some issues with auth with new sonatype host, addressed in this comment below - 
https://issues.sonatype.org/browse/OSSRH-76161?focusedCommentId=1123117&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1123117
Build failed with 401, reverting the release commits created to recreate `10.12` release
> WFESO-4501 - revert failed release commits

- pom.xml
This reverts commit 4aa2911c7b8e8091f4aae5b19342ccc3b5bcaa6b.
Since the new ossrh host has some issues with auth, we will retry using the old host
> Revert "WFESO-4015: update ossrh host to mitigate timeouts (#681)"

- pom.xml
Bumps log4j-api from 2.16.0 to 2.17.0.
---
updated-dependencies:
- dependency-name: org.apache.logging.log4j:log4j-api
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
> Bump log4j-api from 2.16.0 to 2.17.0 (#690)

- proxy/pom.xml
pom.xml has the following
- maven-release-plugin for auto increment of build versions
- Create commits and push release tags
- Add developer information
- SCM information
- Enabled sonatype uploads
> enable maven-release-plugin and other changes in pom.xml for new build system

- proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
- proxy/src/main/java/com/wavefront/agent/ProxyCheckInScheduler.java
- proxy/src/main/java/com/wavefront/agent/ProxyConfig.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
- proxy/src/main/java/com/wavefront/agent/api/APIContainer.java
- proxy/src/main/java/com/wavefront/agent/handlers/AbstractReportableEntityHandler.java
- proxy/src/main/java/com/wavefront/agent/handlers/DeltaCounterAccumulationHandlerImpl.java
- proxy/src/main/java/com/wavefront/agent/handlers/EventHandlerImpl.java
- proxy/src/main/java/com/wavefront/agent/handlers/HandlerKey.java
- proxy/src/main/java/com/wavefront/agent/handlers/HistogramAccumulationHandlerImpl.java
- proxy/src/main/java/com/wavefront/agent/handlers/ReportPointHandlerImpl.java
- proxy/src/main/java/com/wavefront/agent/handlers/ReportSourceTagHandlerImpl.java
- proxy/src/main/java/com/wavefront/agent/handlers/ReportableEntityHandlerFactoryImpl.java
- proxy/src/main/java/com/wavefront/agent/handlers/SenderTaskFactory.java
- proxy/src/main/java/com/wavefront/agent/handlers/SenderTaskFactoryImpl.java
- proxy/src/main/java/com/wavefront/agent/handlers/SpanHandlerImpl.java
- proxy/src/main/java/com/wavefront/agent/handlers/SpanLogsHandlerImpl.java
- proxy/src/main/java/com/wavefront/agent/handlers/TrafficShapingRateLimitAdjuster.java
- proxy/src/main/java/com/wavefront/agent/queueing/QueueingFactoryImpl.java
- proxy/src/test/java/com/wavefront/agent/ProxyCheckInSchedulerTest.java
- proxy/src/test/java/com/wavefront/agent/PushAgentTest.java
- proxy/src/test/java/com/wavefront/agent/api/APIContainerTest.java
- proxy/src/test/java/com/wavefront/agent/handlers/ReportSourceTagHandlerTest.java
This is feature request from Dell Dimension ([Jira](https://wavefront.atlassian.net/browse/MONIT-25479))
Changes summary:
- Refactored `ProxyConfig` and `APIContainer` so that we can config multicasting tenants.
- Refactored `HandlerKey` to include tenant name.
- Main refactoring at `SenderTaskFacotryImpl` where it initiates tenant specific `SenderTask` and `QueueController`.
- Refactored the `reportInternal()` function of various data type's `ReportableEntityHandler` where we check the tag key `multicastingTenantName` to decide if corresponding data should be multicasted.
- example config file:
```
retryThreads=0
server=https://surf.wavefront.com/api
hostname=xiaochen_laptop
token=<surf_token>
pushListenerPorts=2878
deltaCountersAggregationListenerPorts = 12878 …
```
> Multicasting - xiaochenw/monit 25479

- proxy/src/main/java/com/wavefront/agent/handlers/SpanHandlerImpl.java
To test span is rejected when start time exceeds 24 hours, run:
`echo "test-span-24-hours-ahead source=test-source traceId=7b3bf470-9456-11e8-9eb6-529269fb1513 spanId=0313bafe-9457-11e8-9eb6-529269fb1459 parent=2f64e538-9457-11e8-9eb6-529269fb1459 application=Wavefront service=istio cluster=none shard=none http.method=GET <time-in-milliseconds> <duration-in-milliseconds>" | curl -H "Authorization: Bearer <token>" --data @- https://<cluster>.wavefront.com:30000/report`
> [MONIT-26336] Add span future fill limit of 24 hours

- proxy/src/main/java/com/wavefront/agent/preprocessor/ReportPointExtractTagTransformer.java
- proxy/src/test/java/com/wavefront/agent/preprocessor/PreprocessorRulesTest.java
Fixes source as pointLine for addTag and addTagIfNotExists Preprocessor Rules. https://docs.wavefront.com/proxies_preprocessor_rules.html#extracttag-and-extracttagifnotexists
Testing:
1. Add the following to proxy/preprocessor_rules.yaml:
```
- rule : extract-tenantfinal
action : extractTagIfNotExists
source : pointLine
tag : newAddedTag
search : ".*device.*"
replace : "newTag"
```
2. Confirm that new tag newAddedTag is added to metric with value newTag when metric name, source name or point tag value matches search regex.
3. When `action: extractTag` and tag newAddedTag already exists, confirm new value is set.
4. When `action: extractTagIfNotExists` and tag newAddedTag already exists, confirm original value is kept.
> [MONIT-28676] Fix pointline for extractTag and extractTagIfNotExists

- proxy/src/main/java/com/wavefront/agent/preprocessor/ReportPointExtractTagTransformer.java
- proxy/src/test/java/com/wavefront/agent/preprocessor/PreprocessorRulesTest.java
This commit includes point tag key in search, as source=pointLine rule applies to the whole point line.
Testing:
Add the following to proxy/preprocessor_rules.yaml:
```
- rule : extract-tenantfinal
action : extractTagIfNotExists
source : pointLine
tag : newAddedTag
search : ".*device.*"
replace : "newTag"
```
Confirm that new tag newAddedTag is added to metric with value newTag when **point tag key** matches search regex.
When action: extractTag and tag newAddedTag already exists, confirm new value is set.
When action: extractTagIfNotExists and tag newAddedTag already exists, confirm original value is kept.
> [MONIT-29838] ExtractTag and extractTagIfNotExists Preprocessor Update

- proxy/src/main/java/com/wavefront/agent/listeners/otlp/OtlpMetricsUtils.java
- proxy/src/test/java/com/wavefront/agent/listeners/otlp/OtlpMetricsUtilsTest.java
Prior to this fix, we assumed data points in OpenTelemetry metrics always had double values. If a data point instead had an int/long value, the resulting WF metric would have a likely incorrect value of 0.0.
> Accept OpenTelemetry metrics with int/long values

- proxy/pom.xml
- proxy/src/main/java/com/wavefront/agent/ProxyConfig.java
- proxy/src/main/java/com/wavefront/agent/PushAgent.java
- proxy/src/test/java/com/wavefront/agent/HttpEndToEndTest.java
- changes to ingested "error_name" instead of "exception" for summary
- User can provide custom exception and log level tags names for alert summary page.
> MONIT-30269: changes to ingested "error_name" instead of "exception" for summary

- README.md
- proxy/pom.xml
On the released tags tarball 11.4 and 12.0, `mvn -f proxy clean install -DskipTest` fails to execute format-code on project proxy because it expects the source to be git repository. 
> [ERROR] Failed to execute goal com.cosium.code:git-code-format-maven-plugin:3.3:format-code (format-code) on project proxy: Execution format-code of goal com.cosium.code:git-code-format-maven-plugin:3.3:format-code failed: One of setGitDir or setWorkTree must be called. -> [Help 1]
Added the PR to skip this in proxy/pom.xml while doing mvn install. 
`mvn -f proxy clean install -DskipTests -DskipFormatCode` skips the format code for a released tarball.
> proxy-pom.xml: skip format-code plugin

- proxy/pom.xml
- proxy/src/main/java/com/wavefront/agent/formatter/DataFormat.java
- proxy/src/main/java/com/wavefront/agent/listeners/AbstractLineDelimitedHandler.java
- proxy/src/main/java/com/wavefront/agent/listeners/WavefrontPortUnificationHandler.java
- proxy/src/test/java/com/wavefront/agent/HttpEndToEndTest.java
Add support for new format `logs_json_lines`.
Update handling of HTTP messages to process JsonLines along with JsonArray.
Add an integration test to check JsonLines logs processing.
Update discarded Http-messages counts while ingesting `fluentBit` logs.
Update receivedLogsBatches count for `fluentBit` logs batches.
> deosu/monit 31993: add fluentBit support

- proxy/pom.xml
- proxy/src/main/java/com/wavefront/agent/data/LogDataSubmissionTask.java
Add a logger in LogDataSubmissionTask and log a payload before it is sent to the backend(if the root logger's level is defined as DEBUG).
> MONIT-31965 Add debug level payload logging

- proxy/src/test/java/com/wavefront/agent/PushAgentTest.java
When playing with the `tlsPorts` functionality and commenting out parts of the implementation, I found that `mvn clean test` would seem to hang forever. I tracked it down to `PushAgentTest`. This PR adds a 5 second timeout for each test in that class, so that the test suite continues running instead of hanging.
Output when there are timeout failures looks like:
```
[ERROR] Errors:
[ERROR] com.wavefront.agent.PushAgentTest.testSecureAll
[ERROR]   Run 1: PushAgentTest.testSecureAll:250 » TestTimedOut test timed out after 5 seconds
[ERROR]   Run 2: PushAgentTest.testSecureAll:250 » TestTimedOut test timed out after 5 seconds
[ERROR]   Run 3: PushAgentTest.testSecureAll:250 » TestTimedOut test timed out after 5 seconds
[ERROR]   Run 4: PushAgentTest.testSecureAll:250 » TestTimedOut test timed …
```
> Add 5 second timeout for PushAgent tests

- proxy/pom.xml
- proxy/src/main/java/com/wavefront/agent/formatter/DataFormat.java
- proxy/src/main/java/com/wavefront/agent/listeners/AbstractLineDelimitedHandler.java
- proxy/src/main/java/com/wavefront/agent/listeners/WavefrontPortUnificationHandler.java
- proxy/src/test/java/com/wavefront/agent/HttpEndToEndTest.java
Update the proxy to read logs with a format(logs_json_cloudwatch).
This code change has a dependency on the next java-lib release(which should be released soon). If the latest java-lib release is not `2023-01.1`, then we need to get java-lb changes locally from the feature branch and build the java-lib jar. Then build the proxy jar with the following command. 
`mvn clean install:install-file -Dfile=<path to your java-lib jar> \
-DgroupId=com.wavefront \
-DartifactId=java-lib \
-Dversion=2023-01.1 \
-Dpackaging=jar`
> MONIT 32316 process cloud watch logs

- proxy/pom.xml
- proxy/src/test/java/com/wavefront/agent/logsharvesting/LogsIngesterTest.java
- explicitly add dependency on snakeyaml since we import it directly in the code
- update test to use explict loadOptions on the YamlFactory for the objectmapper
> MONIT-34093 - Upgrade to snakeyaml 2.0 for CVE-2022-1471

- proxy/src/main/java/com/wavefront/agent/ProxyCheckInScheduler.java
- proxy/src/main/java/com/wavefront/agent/ProxySendConfigScheduler.java
https://jira.eng.vmware.com/browse/MONIT-34005
> Monit 34005: Fix crash on bad URL config

- proxy/pom.xml
Looks like it was caused by this PR: https://github.com/wavefrontHQ/wavefront-proxy/pull/839
> [MONIT-34586] Fix Filebeat integration throwing an exception

- proxy/src/main/java/com/wavefront/agent/ProxyConfig.java
- proxy/src/main/java/com/wavefront/agent/TokenWorkerCSP.java
- proxy/src/main/java/com/wavefront/agent/api/CSPAPI.java
- proxy/src/test/java/com/wavefront/agent/ProxyConfigTest.java
- proxy/src/test/java/com/wavefront/agent/TenantInfoTest.java
Making csp orgId optional by default. Added tests with this functionality. Fixed a couple of typos.
> Making csp orgId optional by default for the proxy
