proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
proxy/src/main/java/com/wavefront/agent/PushAgent.java

@conorbev  requested a better name

Rename blacklist/whitelist conf file params, but maintain compatibility

---

proxy/src/main/java/com/wavefront/agent/PointHandler.java
proxy/src/test/java/com/wavefront/agent/PointHandlerTest.java

@panghy please review and pull.  thx.

MONIT-2250 restrict metric names to AlphaNumeric and _-,./ at agent

---

java-lib/src/main/java/com/wavefront/api/AgentAPI.java

@panghy 
Can you merge and make a new Maven release?

Add @Valid annotation to AgentAPI for Jersey conformance

---

proxy/src/main/java/com/wavefront/agent/PointHandler.java
proxy/src/test/java/com/wavefront/agent/PointHandlerTest.java

@panghy 
The validation is definitely faster.  But now there's more =)  Hopefully it will balance out.

Faster validations + add validation for point tag keys

---

java-lib/src/main/java/com/wavefront/api/agent/AgentConfiguration.java
proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
proxy/src/main/java/com/wavefront/agent/ChannelStringHandler.java
proxy/src/main/java/com/wavefront/agent/JsonMetricsEndpoint.java
proxy/src/main/java/com/wavefront/agent/PointHandler.java
proxy/src/main/java/com/wavefront/agent/PostPushDataTimedTask.java
proxy/src/main/java/com/wavefront/agent/PushAgent.java
proxy/src/main/java/com/wavefront/agent/QueuedAgentService.java
proxy/src/test/java/com/wavefront/agent/QueuedAgentServiceTest.java

Allow batch size and retry exponential backoff to be dynamically configurable by collector

---

pkg/README.md
pkg/build.sh
pkg/etc/init.d/wavefront-proxy

Tested on Ubuntu 14.10 and CentOS 7.

Remove packr from the wavefront proxy build process.

---

pkg/etc/init.d/wavefront-proxy
proxy/pom.xml
proxy/src/main/java/com/wavefront/agent/QueuedAgentService.java

Also fix proxy/pom.xml so that intellij cleanly builds this project.

Improve UX when single agent is used for high load.

---

proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
proxy/src/main/java/com/wavefront/agent/PostPushDataTimedTask.java

Additional metrics to help identify stuck flush threads

Track batches counter for every flush thread

---

proxy/src/main/java/com/wavefront/agent/ChannelStringHandler.java
test/runner.py

2 small changes:
1 - ChannelStringHandler: added exception handler implementation to log something when exception occurs.  Added this when trying to debug an issue at a customer.
2 - test runner: ran pylint and corrected all warnings

Update Handler to log on exceptions and fix test runner pylint issues

---

proxy/config.ini
proxy/src/main/java/com/wavefront/agent/PointHandlerImpl.java
proxy/src/test/java/com/wavefront/agent/PointHandlerTest.java

This yeilds a 50% throughput boost on my MBP.
Related:
http://stackoverflow.com/questions/513600/should-i-use-javas-string-format-if-performance-is-important

Change pointToString impl to use StringBuilder instead of String.format.

---

pkg/stage.sh
pom.xml
proxy/pom.xml

Clean up zombie maven rules, improve release process

---

proxy/src/main/java/com/wavefront/agent/PointHandlerImpl.java
proxy/src/main/java/com/wavefront/agent/PostPushDataTimedTask.java

of retry queues with tiny batches in high-volume environments

Soft-block buffers when draining to queue to prevent oversaturation

---

proxy/docker/run.sh

If the proxy process dies, so will the container, which is best practice for docker use-case.

Changed run.sh so that java process is attached to stdout

---

proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
proxy/src/main/java/com/wavefront/agent/PushAgent.java
proxy/src/main/java/com/wavefront/agent/config/LogsIngestionConfig.java
proxy/src/main/java/com/wavefront/agent/logsharvesting/FilebeatListener.java

Better handling of configuration errors.

---

java-lib/src/main/java/com/wavefront/ingester/GraphiteHostAnnotator.java

This implementation is about 60x-70x faster than regex match in the optimistic scenario (2 custom source tags as in default config, "source=" present), and still about 12x faster in the pessimistic scenario (10 custom source tags, no source). 
Not performing case insensitive comparison did help boost the performance as it is not really useful here, as annotations dictionaries are case-sensitive anyway.

Improve GraphiteHostAnnotator performance

---

java-lib/src/main/java/com/wavefront/ingester/PickleProtocolDecoder.java
pkg/after-install.sh
pkg/etc/init.d/wavefront-proxy
pkg/etc/wavefront/wavefront-proxy/log4j2-stdout.xml.default
pkg/etc/wavefront/wavefront-proxy/log4j2.xml.default
proxy/pom.xml
proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
proxy/src/main/java/com/wavefront/agent/ChannelByteArrayHandler.java
proxy/src/main/java/com/wavefront/agent/ChannelStringHandler.java
proxy/src/main/java/com/wavefront/agent/JsonMetricsEndpoint.java
proxy/src/main/java/com/wavefront/agent/PointHandlerImpl.java
proxy/src/main/java/com/wavefront/agent/PostPushDataTimedTask.java
proxy/src/main/java/com/wavefront/agent/PushAgent.java
proxy/src/main/java/com/wavefront/agent/QueuedAgentService.java
proxy/src/main/java/com/wavefront/agent/Validation.java
proxy/src/main/java/com/wavefront/agent/WriteHttpJsonMetricsEndpoint.java
proxy/src/main/java/com/wavefront/agent/preprocessor/ReportPointTimestampInRangeFilter.java
proxy/src/test/java/com/wavefront/agent/QueuedAgentServiceTest.java

- Switch to log4j2 library (with java.util.logging and slf4j adapters) 
- More user-friendly error messages to assist with troubleshooting
- Add ability to log raw blocked points to correct and replay later
- Enable log rotation with reasonable defaults (rotate logs once a day or when exceed 100MB)  
- Change log format to 1 line per entry (with ability to revert to use old format)

Refactor logging

---

pkg/etc/wavefront/wavefront-proxy/preprocessor_rules.yaml.default
proxy/pom.xml
proxy/src/main/java/com/wavefront/agent/QueuedAgentService.java
proxy/src/main/java/com/wavefront/agent/preprocessor/AgentPreprocessorConfiguration.java
proxy/src/main/java/com/wavefront/agent/preprocessor/ReportPointExtractTagTransformer.java
proxy/src/test/java/com/wavefront/agent/QueuedAgentServiceTest.java
proxy/src/test/java/com/wavefront/agent/preprocessor/AgentConfigurationTest.java
proxy/src/test/java/com/wavefront/agent/preprocessor/PreprocessorRulesTest.java
proxy/src/test/resources/com/wavefront/agent/preprocessor/preprocessor_rules.yaml
proxy/src/test/resources/com/wavefront/agent/preprocessor/preprocessor_rules_invalid.yaml
proxy/src/test/resources/log4j2-dev.xml

also, improve logging for unit tests (maven-surefire plugin)

Add extractTag preprocessor rule

---

pkg/etc/wavefront/wavefront-proxy/preprocessor_rules.yaml.default

Added new example to replace something from within the middle of a string. Can be difficult to come up with naturally

Added new example

---

java-client/pom.xml
java-client/src/main/java/com/wavefront/integrations/Wavefront.java

Removed dep on commons-lang:commons-lang

---

pkg/after-install.sh
pkg/etc/init.d/wavefront-proxy

Set log files owner to proxy user 

---

proxy/logsIngestion.yaml
proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
proxy/src/main/java/com/wavefront/agent/PointHandlerImpl.java
proxy/src/main/java/com/wavefront/agent/PushAgent.java
proxy/src/main/java/com/wavefront/agent/logsharvesting/InteractiveLogsTester.java
proxy/src/main/java/com/wavefront/agent/logsharvesting/LogsIngester.java
proxy/src/test/java/com/wavefront/agent/logsharvesting/LogsIngesterTest.java

In a new mode, read lines from STDIN and for each line print every match for that line in logsIngestionConfig.yaml
e.g. java -jar target/proxy-4.5-SNAPSHOT-uber.jar -f config.ini --testLogs < foo.txt
where foo.txt has, e.g.
```
notmatched
counter bar 2
counter foo 42
...
```
May also omit the last bit "< foo.txt" to use interactive terminal mode

Interactive grok debugging

---

java-client/pom.xml
java-client/src/main/java/com/wavefront/integrations/Main.java
java-client/src/main/java/com/wavefront/integrations/Wavefront.java
java-lib/src/main/java/com/wavefront/metrics/ReconnectingSocket.java
yammer-metrics/src/main/java/com/wavefront/integrations/metrics/SocketMetricsProcessor.java

the user for Wavefront client library.

Try to reconnect on broken connections before throwing an exception to

---

pom.xml

@moribellamy Please review and merge.

MONIT-6312: Upgraded the jetty version for OSSTP.

---

proxy/src/test/java/com/wavefront/agent/SourceTagHandlerTest.java

Fixed a minor issue, where the tests failed if run concurrently.

MONIT-5441: Fixed the unit test, so that the tests can run concurrently.

---

java-lib/src/main/java/com/wavefront/common/MetricsToTimeseries.java
java-lib/src/main/java/com/wavefront/metrics/JsonMetricsGenerator.java
yammer-metrics/src/main/java/com/wavefront/integrations/metrics/WavefrontYammerMetricsReporter.java

fix https://github.com/wavefrontHQ/java/issues/187

---

proxy/src/main/java/com/wavefront/agent/AbstractAgent.java

default to 10s to match collectors (PUB-106)

Configurable maxBurstSeconds for the rate limiter

---

pkg/etc/init.d/wavefront-proxy

(Don't exit the script on an off chance of a false positive)

Warn when attempting to start service in docker

---

proxy/src/main/java/com/wavefront/agent/OpenTSDBPortUnificationHandler.java

QA: 'version' cmd by itself should work

Bug fix to make sure version command works

---

java-lib/src/main/java/com/yammer/metrics/core/WavefrontHistogram.java
java-lib/src/test/java/com/wavefront/metrics/JsonMetricsGeneratorTest.java
proxy/src/test/java/com/wavefront/agent/logsharvesting/LogsIngesterTest.java
yammer-metrics/src/test/java/com/wavefront/integrations/metrics/WavefrontYammerMetricsReporterTest.java

Make WavefrontHistogram more performant by reducing contention on synchronized code

---

java-lib/src/main/java/com/wavefront/common/MetricsToTimeseries.java
java-lib/src/main/java/com/wavefront/metrics/JsonMetricsGenerator.java
yammer-metrics/src/main/java/com/wavefront/integrations/metrics/WavefrontYammerMetricsReporter.java

Use better naming and comments.

Use intermittent in-memory structure to store gauges.

---

java-lib/src/main/antlr4/DSLexer.g4
java-lib/src/main/avro/Reporting.avdl
java-lib/src/main/java/com/wavefront/ingester/AbstractIngesterFormatter.java
proxy/src/main/java/com/wavefront/agent/Validation.java
proxy/src/test/java/com/wavefront/agent/PointHandlerTest.java
proxy/src/test/java/com/wavefront/agent/preprocessor/PreprocessorRulesTest.java

Made proxy changes to allow ingesting delta (∆) metrics.

Add delta support for counters

---

pkg/after-install.sh
pkg/after-remove.sh

Added support for opensuse support to install wavefront proxy.
https://wavefront.atlassian.net/browse/MONIT-7898

opensuse support

---

java-client/src/main/java/com/wavefront/integrations/AbstractDirectConnectionHandler.java
java-client/src/main/java/com/wavefront/integrations/AbstractProxyConnectionHandler.java
java-client/src/main/java/com/wavefront/integrations/Wavefront.java
java-client/src/main/java/com/wavefront/integrations/WavefrontConnectionHandler.java
java-client/src/main/java/com/wavefront/integrations/WavefrontDirectSender.java
java-client/src/main/java/com/wavefront/integrations/WavefrontSender.java

Separated connection logic and processing/reporting logic:
- Added a new WavefrontConnectionHandler interface for handling proxy/direct connection logic
- WavefrontSender now extends the WavefrontConnectionHandler interface
- Added new AbstractProxyConnectionHandler and AbstractDirectConnectionHandler to allow better code reuse across different data formats.
- Finally Wavefront and WavefrontDirectSender classes now extend the respective abstract base classes.

Refactor java client code for better code reuse

---

dropwizard-metrics/dropwizard-metrics/README.md

Updated dropwizard README to clarify compatible versions and to include clear examples for reporting to proxy/direct ingestion.

Updated dropwizard metrics README

---

.gitignore
examples/dropwizard-metrics5/pom.xml

Somehow, I can't find Nara in the reviewer list.....

modify .gitignore and fix pom.xml of examples/dropwizard-metric5 module

---

pkg/etc/wavefront/wavefront-proxy/wavefront.conf.default
proxy/docker/Dockerfile
proxy/docker/README.md
proxy/docker/run.sh
proxy/src/main/java/com/wavefront/agent/AbstractAgent.java

- Use latest proxy release for Docker image building
- Allow all properties to be overridden in Docker
- Update config defaults
- Don't use idFile when ephemeral=true

More Docker-friendly configuration

---

proxy/README.md

Corrected typo -- Changed xxListenerPort to xxListenerPorts.

Update README.md file

---

pkg/etc/wavefront/wavefront-proxy/wavefront.conf.default
proxy/src/main/java/com/wavefront/agent/sampler/SpanSamplerUtils.java

MONIT-12724  Fix for Proxy with traceSamplingRate unset and traceSamplingDuration effective will generate unexpected result

---

pom.xml
proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
proxy/src/main/java/com/wavefront/agent/QueuedAgentService.java
proxy/src/test/java/com/wavefront/agent/QueuedAgentServiceTest.java

PUB-153: User-friendly handling for 405 errors

---

pkg/etc/wavefront/wavefront-proxy/log4j2-stdout.xml.default
pkg/etc/wavefront/wavefront-proxy/log4j2.xml.default

also reduce config monitoring interval

Update default logging config for containerized proxies 

---

pkg/etc/wavefront/wavefront-proxy/wavefront.conf.default
proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
proxy/src/main/java/com/wavefront/agent/listeners/tracing/JaegerThriftCollectorHandler.java
proxy/src/main/java/com/wavefront/agent/listeners/tracing/TracePortUnificationHandler.java
proxy/src/main/java/com/wavefront/agent/listeners/tracing/ZipkinPortUnificationHandler.java
proxy/src/test/java/com/wavefront/agent/listeners/tracing/JaegerThriftCollectorHandlerTest.java
proxy/src/test/java/com/wavefront/agent/listeners/tracing/ZipkinPortUnificationHandlerTest.java

issue-411 Count spans discarded by sampler

---

proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
proxy/src/main/java/com/wavefront/agent/config/LogsIngestionConfig.java
proxy/src/main/java/com/wavefront/agent/config/MetricMatcher.java
proxy/src/main/java/com/wavefront/agent/logsharvesting/EvictingMetricsRegistry.java
proxy/src/main/java/com/wavefront/agent/logsharvesting/FlushProcessor.java
proxy/src/main/java/com/wavefront/agent/logsharvesting/LogsIngester.java
proxy/src/test/java/com/wavefront/agent/logsharvesting/LogsIngesterTest.java
proxy/src/test/resources/test.yml

- don't send 0 values for delta counters
- add hostName pattern to override host name from ingested metrics
- allow disabling delta counters to fall back to old functionality
- reduce overhead for hot-reloading logsingestion.yml file
- add --version command line option

Logs ingestion improvements

---

pkg/after-remove.sh
pkg/before-remove.sh

This patch includes -    
1. Service should not stop after upgrading/downgrading
2. Service should not be removed from chkconfig after upgrading/downgrading
https://wavefront.atlassian.net/browse/INT-546
@vikramraman

Fix for INT-546

---

pom.xml
proxy/pom.xml

```
16:31:53 [INFO] [INFO]  * Upload of locally staged artifacts finished.
16:31:53 [INFO] [INFO]  * Closing staging repository with ID "comwavefront-1309".
16:31:53 [INFO] 
16:36:53 [INFO] Waiting for operation to complete..................................................................
16:36:53 [INFO] [WARNING] TIMEOUT
```

revert versions due to sonatype timeout issues

---

pkg/etc/wavefront/wavefront-proxy/wavefront.conf.default
proxy/src/main/java/com/wavefront/agent/ProxyConfig.java
proxy/src/main/java/com/wavefront/agent/PushAgent.java
proxy/src/main/java/com/wavefront/agent/listeners/tracing/CustomTracingPortUnificationHandler.java

to be used for custom tracing port for reporting RED metrics.

Enable configuring default application and service name 

---

proxy/src/main/java/com/wavefront/agent/ProxyConfig.java
proxy/src/main/java/com/wavefront/agent/PushAgent.java

As well as default allow-request-headers and allow-request-methods

Added support for multiple CORS origins

---

proxy/src/main/java/com/wavefront/agent/handlers/ReportPointHandlerImpl.java
proxy/src/main/java/com/wavefront/agent/handlers/SpanHandlerImpl.java

New metric in the proxy to find out how many point/histogram/span tags user is emitting

Metric Tag Count for Points/Histograms/Spans

---

.idea/codeStyleSettings.xml
pom.xml
proxy/src/main/java/com/wavefront/agent/handlers/ReportableEntityHandlerFactoryImpl.java
proxy/src/main/java/com/wavefront/agent/handlers/SpanHandlerImpl.java
proxy/src/main/java/com/wavefront/agent/listeners/WavefrontPortUnificationHandler.java
proxy/src/main/java/com/wavefront/agent/listeners/tracing/SpanUtils.java
proxy/src/main/java/com/wavefront/agent/listeners/tracing/TracePortUnificationHandler.java
proxy/src/main/java/com/wavefront/agent/preprocessor/InteractivePreprocessorTester.java
proxy/src/test/java/com/wavefront/agent/listeners/tracing/SpanUtilsTest.java

* Move span validation part from SpanHandlerImpl to SpanUtils.
* Improve test coverage.

Support oversized annotation values for spans

---

pom.xml

Update AWS SDK to 1.11.946 to support web identity tokens

---

pkg/Dockerfile

https://wavefront.atlassian.net/browse/ESO-3222

ESO:3222: change gpg keyserver from hkp://keys.gnupg.net to keyserver.ubuntu.com

---

pom.xml
proxy/pom.xml
proxy/src/main/java/com/wavefront/agent/handlers/InternalProxyWavefrontClient.java

https://appcheck.eng.vmware.com/#/product/300283/analysis

security updates

---

proxy/src/main/java/com/wavefront/agent/AbstractAgent.java
proxy/src/main/java/com/wavefront/agent/ProxyCheckInScheduler.java
proxy/src/main/java/com/wavefront/agent/handlers/SenderTaskFactoryImpl.java
proxy/src/test/java/com/wavefront/agent/ProxyCheckInSchedulerTest.java

Changes to merge into MONIT-23859 PR#668

Proxy Truncation Code + Logging Statments

---

proxy/pom.xml
proxy/src/main/java/com/wavefront/agent/config/MetricMatcher.java
proxy/src/test/java/com/wavefront/agent/logsharvesting/LogsIngesterTest.java

Analysis: https://appcheck.eng.vmware.com/#/product/370521/analysis

Update dependencies versions for V11.0

---

proxy/pom.xml

Fix derived from this issue - 
https://github.com/streamnative/kop/issues/1015
Fix - https://github.com/streamnative/kop/pull/1018

update pom.xml with default javadoc for sonatype

---

proxy/pom.xml

This reverts commit 91c5777b91d8520bf849622ffbdcb4bbfbc252be.

Revert "Temporary fix to skip upload to nexus for 11.1. Revert later (#741)"

---

proxy/src/test/java/com/wavefront/agent/PushAgentTest.java

Remove @Ignore annotation after fixes

Passing 12 more unit tests in PushAgentTest

---

.github/workflows/mac_tarball_notarization.yml
macos_proxy_notarization/proxy_notarization.sh

based on this PR - https://github.com/wavefrontHQ/wavefront-proxy/pull/753
and https://jira.eng.vmware.com/browse/MONIT-27734

Fix macos notarization according to new packaging

---

.github/workflows/mac_tarball_notarization.yml
macos_proxy_notarization/proxy_notarization.sh

This reverts commit 8235d62929493bae250588cd71855190e38f148c.

Revert "Fix macos notarization according to new packaging (#785)"

---

proxy/pom.xml
proxy/src/main/java/com/wavefront/agent/ProxyCheckInScheduler.java
proxy/src/main/java/com/wavefront/agent/ProxyConfig.java
proxy/src/main/java/com/wavefront/agent/ProxyConfigDef.java
proxy/src/main/java/com/wavefront/agent/PushAgent.java
proxy/src/main/java/com/wavefront/agent/api/APIContainer.java
proxy/src/main/java/com/wavefront/agent/listeners/FeatureCheckUtils.java
proxy/src/main/java/com/wavefront/agent/listeners/WavefrontPortUnificationHandler.java
proxy/src/test/java/com/wavefront/agent/HttpEndToEndTest.java
proxy/src/test/java/com/wavefront/agent/ProxyCheckInSchedulerTest.java
proxy/src/test/java/com/wavefront/agent/api/APIContainerTest.java

Please check the acceptance criteria of [MONIT-33770](https://jira.eng.vmware.com/browse/MONIT-33770)

MONIT-33770: Proxy Ingest w/o Admin Auth

---

proxy/src/main/java/com/wavefront/agent/TenantInfo.java

We will add unit tests when the review is complete.

MONIT-35749: Enhance the proxy change error handling technique for CSP customers.

---

README.md

MONIT-36115 - Update README.md to include logs

---

proxy/src/main/java/com/wavefront/agent/ProxyConfig.java

When requesting the proxy configuration file using the Wavefront UI or an API call, the responce always includes the token value. We'll now cover it up and only display the final four digits. For cspAppId, cspAppSecret, and cspAPIToken, the same applies.

MONIT-40976: Hide Proxy UI tokens in 13.0
